### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Oten-arch** [eosphoros-ai/Awesome-Text2SQL#19]
麻烦写的时候在论文后面标注一下实验用到的数据集名称

**Comment by junewgl** [comment]
好的，后面整理一下

**Comment by csunny** [comment]
@Oten-arch  已经按建议更新， Awesome希望围绕数据领域打造一个优秀的内容社区，如果有更多的建议或者想法，也非常欢迎更我们一起共建。
