### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Forest-Lee** [eosphoros-ai/Awesome-Text2SQL#45]
BIRD-VES测试的rk2: [MAC-SQL](https://github.com/wbbeyourself/MAC-SQL)已经发布了[论文](https://arxiv.org/abs/2312.11242)，可以更新一下😁

**Comment by junewgl** [comment]
> BIRD-VES测试的rk2: [MAC-SQL](https://github.com/wbbeyourself/MAC-SQL)已经发布了[论文](https://arxiv.org/abs/2312.11242)，可以更新一下😁

Great! Thank you for your suggestion. We have submitted this part of the code for reference [PR/46](https://github.com/eosphoros-ai/Awesome-Text2SQL/pull/46). If you have other good suggestions or ideas, we welcome you to contribute PR, Issue, etc. @Forest-Lee
