### ISSUE TITLE
Proposal to add text2sql library

### ISSUE THREAD

**Issue by Anindyadeep** [eosphoros-ai/Awesome-Text2SQL#70]
Hi, we just open-sourced a library for text2sql last week. Currently, we only offer evaluation, but we are also shipping more features first. Would love to see as an addition in this repo (under library section).

**Comment by junewgl** [comment]
Cool, you can submit a PR, refer to mindsql, and put the library name and introduction after the mindsql library. Looking forward to your contribution! @Anindyadeep

**Comment by Anindyadeep** [comment]
Sure thanks :)
